In [4]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [5]:
!ls

AIVoiceCall.ipynb  callCenterDataset.xlsx
aiVoiceCall.py	   customerCallTranscriptions.csv

In [6]:
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in /home/aatif/.local/lib/python3.10/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /home/aatif/.local/lib/python3.10/site-packages (from openpyxl) (2.0.0)

## Dataset 1

In [7]:
df1 = pd.read_excel('callCenterDataset.xlsx')

In [8]:
df1.head()

,Call Id,Agent,Date,Time,Topic,Answered (Y/N),Resolved,Speed of answer in seconds,AvgTalkDuration,Satisfaction rating
0,ID0001,Diane,2021-01-01,09:12:58,Contract related,Y,Y,109.0,00:02:23,3.0
1,ID0002,Becky,2021-01-01,09:12:58,Technical Support,Y,N,70.0,00:04:02,3.0
2,ID0003,Stewart,2021-01-01,09:47:31,Contract related,Y,Y,10.0,00:02:11,3.0
3,ID0004,Greg,2021-01-01,09:47:31,Contract related,Y,Y,53.0,00:00:37,2.0
4,ID0005,Becky,2021-01-01,10:00:29,Payment related,Y,Y,95.0,00:01:00,3.0

In [9]:
df1.shape

(5000, 10)

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Call Id                     5000 non-null   object
 1   Agent                       5000 non-null   object
 2   Date                        5000 non-null   object
 3   Time                        5000 non-null   object
 4   Topic                       5000 non-null   object
 5   Answered (Y/N)              5000 non-null   object
 6   Resolved                    5000 non-null   object
 7   Speed of answer in seconds  4054 non-null   float64
 8   AvgTalkDuration             4054 non-null   object
 9   Satisfaction rating         4054 non-null   float64
dtypes: float64(2), object(8)
memory usage: 390.8+ KB

In [11]:
df1.isnull().sum()

Call Id                         0
Agent                           0
Date                            0
Time                            0
Topic                           0
Answered (Y/N)                  0
Resolved                        0
Speed of answer in seconds    946
AvgTalkDuration               946
Satisfaction rating           946
dtype: int64

In [12]:
df1_cleaned = df1.dropna()

In [13]:
df1_cleaned.shape

(4054, 10)

In [14]:
df1_cleaned['Topic'].value_counts()

Topic
Streaming            847
Payment related      818
Technical Support    805
Admin Support        795
Contract related     789
Name: count, dtype: int64

### Dataset 2

In [15]:
df2 = pd.read_csv('customerCallTranscriptions.csv')

In [16]:
df2.head()

                                                text sentiment_label
0  how's it going Arthur I just placed an order w...        negative
1  yeah hello I'm just wondering if I can speak t...         neutral
2  hey I receive my order but it's the wrong size...        negative
3  hi David I just placed an order online and I w...         neutral
4  hey I bought something from your website the o...        negative

In [17]:
df2['sentiment_label'].value_counts()

sentiment_label
neutral     57
negative    43
positive     2
Name: count, dtype: int64

In [18]:
negative_row = df2.iloc[0,:]

print("Text :",negative_row['text'])
print("Sentiment Label :",negative_row['sentiment_label'])

Text : how's it going Arthur I just placed an order with you guys and I accidentally sent it to the wrong address can you please help me change this
Sentiment Label : negative

In [19]:
positive_row = df2.iloc[16,:]

print("Text :",positive_row['text'])
print("Sentiment Label :",positive_row['sentiment_label'])

Text : I'm just happy with the colour that I got from you guys so is there any chance I can change it for a different one
Sentiment Label : positive

In [20]:
neutral_row = df2.iloc[1,:]

print("Text :",neutral_row['text'])
print("Sentiment Label :",neutral_row['sentiment_label'])

Text : yeah hello I'm just wondering if I can speak to someone about an order I received yesterday
Sentiment Label : neutral

In [21]:
df2.shape

(102, 2)

In [22]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   text             102 non-null    object
 1   sentiment_label  102 non-null    object
dtypes: object(2)
memory usage: 1.7+ KB

In [23]:
df2.isnull().sum()

text               0
sentiment_label    0
dtype: int64